In [171]:
import imageio
import torch
import numpy as np

In [172]:
img_arr = imageio.imread("C:\\Users\\ulrik\\Desktop\\progging\\Datasets\\bobby.jpg")
img_arr.shape

C:\Users\ulrik\AppData\Local\Temp\ipykernel_5668\4253128736.py:1: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread("C:\\Users\\ulrik\\Desktop\\progging\\Datasets\\bobby.jpg")


(878, 1200, 3)

In [173]:
img = torch.from_numpy(img_arr)
out = img.permute(2,0,1)

In [174]:
batch_size = 3
batch = torch.zeros(batch_size, 3, 256, 256, dtype=torch.uint8)

In [175]:
path = "C:\\Users\\ulrik\\Desktop\\progging\\Datasets\\winequality-white.csv"



In [176]:
import pandas as pd
df = pd.read_csv(path, sep=";")
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  
0         8.8        6  
1         9.5        6  
2        10.1        6  
3         9.9        6  
4         9.9        6  
...       ...      ...  
4893     11.2        6  
4894      9.6        5  
4895      9.4        6  
4896     12.8        7  
4897     11.8        6  

[4898 rows x 12 columns]

In [177]:
import csv
wineq_numpy = np.loadtxt(path, dtype=np.float32, delimiter=";", skiprows=1)
wineq_numpy

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [178]:
col_list = next(csv.reader(open(path), delimiter=";"))
wineq_numpy.shape, col_list

((4898, 12),
 ['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol',
  'quality'])

In [179]:
wineq = torch.from_numpy(wineq_numpy)
wineq.shape, wineq.dtype

(torch.Size([4898, 12]), torch.float32)

In [180]:
data = wineq[:,: -1]
data, data.shape

(tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
         [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
         [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
         ...,
         [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
         [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
         [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]]),
 torch.Size([4898, 11]))

In [181]:
target = wineq[:, -1].long()
target

tensor([6, 6, 6,  ..., 6, 7, 6])

In [182]:
target_onehot = torch.zeros(target.shape[0], 10)

In [183]:
target_onehot.scatter_(1, target.unsqueeze(1), 1)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [184]:
bad_indexes = target <= 3
bad_indexes.shape, bad_indexes.dtype, bad_indexes.sum()

(torch.Size([4898]), torch.bool, tensor(20))

In [185]:
bad_data = data[bad_indexes]
bad_data.shape

torch.Size([20, 11])

In [186]:
mid_data = data[(target > 3) & (target < 7)]
good_data = data[target >= 7]

In [187]:
bad_mean = torch.mean(bad_data, dim = 0)
mid_mean = torch.mean(mid_data, dim = 0)
good_mean = torch.mean(good_data, dim = 0)

In [188]:
for i, args in enumerate(zip(col_list, bad_mean, mid_mean, good_mean)):
    print("{:2} {:20} {:6.2f} {:6.2f}".format(i, *args))
    

 0 fixed acidity          7.60   6.89
 1 volatile acidity       0.33   0.28
 2 citric acid            0.34   0.34
 3 residual sugar         6.39   6.71
 4 chlorides              0.05   0.05
 5 free sulfur dioxide   53.33  35.42
 6 total sulfur dioxide 170.60 141.83
 7 density                0.99   0.99
 8 pH                     3.19   3.18
 9 sulphates              0.47   0.49
10 alcohol               10.34  10.26


In [189]:
total_sulfur_treshold = 141.83
total_sulfur_data = data[:, 6]
predicted_indexes = torch.lt(total_sulfur_data, total_sulfur_treshold)
predicted_indexes.shape, predicted_indexes.dtype, predicted_indexes.sum()

(torch.Size([4898]), torch.bool, tensor(2727))

In [190]:
actual_indexes = target > 5
actual_indexes.shape, actual_indexes.dtype, actual_indexes.sum()

(torch.Size([4898]), torch.bool, tensor(3258))

In [191]:
n_matches = torch.sum(actual_indexes & predicted_indexes).item()
n_predicted = torch.sum(predicted_indexes).item()
n_actual = torch.sum(actual_indexes).item()

n_matches, n_matches / n_predicted, n_matches / n_actual

(2018, 0.74000733406674, 0.6193984039287906)

In [192]:
bikes_numpy = np.loadtxt(r"C:\Users\ulrik\Desktop\progging\Datasets\bikesharing\hour.csv",
                         dtype=np.float32,
                         delimiter=",",
                         skiprows=1,
                         converters={1:lambda x: float(x[8:10])})
bikes = torch.from_numpy(bikes_numpy)


In [193]:
bikes.shape, bikes.stride()
bikes.size()

torch.Size([17379, 17])

In [194]:
i = 40
while i*24*17 < 295_443:
    i += 1
    if i *408 > 295_443:
        i += -1
        break

    
i *24 * 17

295392

In [195]:
num_rows_del = (295443 - 295392) / 17
num_rows_del

3.0

In [196]:
bikes.shape


torch.Size([17379, 17])

In [197]:
bikes = bikes[:bikes.shape[0] - 3 , :]

In [198]:
daily_bikes = bikes.view(-1,24, bikes.shape[1])
daily_bikes.shape, daily_bikes.stride()

(torch.Size([724, 24, 17]), (408, 17, 1))

In [199]:
daily_bikes = daily_bikes.transpose(1, 2)
daily_bikes.shape, daily_bikes.stride()

(torch.Size([724, 17, 24]), (408, 1, 17))

In [200]:
first_day =  bikes[:24].long()
weather_onehot = torch.zeros(first_day.shape[0], 4)
first_day[: , 9]

tensor([1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2])

In [201]:
weather_onehot.scatter_(
    dim = 1,
    index = first_day[: , 9].unsqueeze(1).long() -1,
    value = 1.0
)

tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]])

In [202]:
torch.cat((bikes[:24], weather_onehot), 1)[:1]

tensor([[ 1.0000,  1.0000,  1.0000,  0.0000,  1.0000,  0.0000,  0.0000,  6.0000,
          0.0000,  1.0000,  0.2400,  0.2879,  0.8100,  0.0000,  3.0000, 13.0000,
         16.0000,  1.0000,  0.0000,  0.0000,  0.0000]])

In [203]:
daily_weather_onehot = torch.zeros(daily_bikes.shape[0], 4,
                                    daily_bikes.shape[2])
daily_weather_onehot.shape

torch.Size([724, 4, 24])

In [204]:
daily_weather_onehot.scatter_(1, daily_bikes[: , 9, : ].long().unsqueeze(1) - 1, 1.0)
daily_weather_onehot.shape

torch.Size([724, 4, 24])

In [205]:
daily_bikes = torch.cat((daily_bikes, daily_weather_onehot), dim = 1)

In [206]:
temp = daily_bikes[:, 10, :]
temp_min = torch.min(temp)
temp_max = torch.max(temp)
daily_bikes[: , 10, :] = ((daily_bikes[:, 10, :] - temp_min )/(temp_max - temp_min))

In [207]:
book = "gutenberg.org_cache_epub_1342_pg1342"
path = "C:\\Users\\ulrik\\Desktop\\progging\\Datasets\\Gutenberg\\"


In [208]:
with open(f"{path}{book}.txt", encoding = "utf8") as f:
    text = f.read()



In [210]:
lines = text.split("\n")
line = lines[200]
line

'for there was a distinctly feminine element in “Mr. Spectator,” and in'

In [211]:
letter_t = torch.zeros(len(line), 128)
letter_t.shape

torch.Size([70, 128])

In [215]:
for i, letter in enumerate(line.lower().strip()):
    letter_index = ord(letter) if (ord(letter) < 128) else 0
    letter_t[i][letter_index] = 1

In [216]:
def clean_words(input_str):
    punctuation = '.,;:"!?_-'
    word_list = input_str.lower().replace('\n','').split()
    word_list = [word.strip(punctuation) for word in word_list]
    return word_list

words_in_line = clean_words(line)
line, words_in_line

('for there was a distinctly feminine element in “Mr. Spectator,” and in',
 ['for',
  'there',
  'was',
  'a',
  'distinctly',
  'feminine',
  'element',
  'in',
  '“mr',
  'spectator,”',
  'and',
  'in'])

In [217]:
word_list = sorted(set(clean_words(text)))
word2index_dict = {word: i for(i, word) in enumerate(word_list)}

len(word2index_dict), word2index_dict["impossible"]

(16745, 7358)

In [223]:
word_t = torch.zeros(len(words_in_line), len(word2index_dict))
for i, word in enumerate(words_in_line):
    word_index = word2index_dict[word]
    word_t[i][word_index] = 1
    print("{} {} {}".format(i, word_index, word))

0 5456 for
1 14176 there
2 15490 was
3 185 a
4 4190 distinctly
5 5284 feminine
6 4503 element
7 7391 in
8 16655 “mr
9 13103 spectator,”
10 885 and
11 7391 in
