In [15]:
import torch

In [16]:
points = torch.tensor([[4, 1],[5, 3], [2, 0]])
second_point = points[1]
second_point.storage_offset()

2

In [17]:
second_point

tensor([5, 3])

In [18]:
second_point.shape

torch.Size([2])

In [19]:
points.stride()

(2, 1)

In [20]:
points.is_contiguous()

True

In [22]:
points_t = points.t()



In [23]:
points_t.is_contiguous()

False

In [28]:
points_gpu = torch.tensor([[4, 1], [5, 3], [2, 1]], device="cuda")

In [29]:
points_gpu = 2 * points.to(device = "cuda")

In [30]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

It also means modifying the NumPy array will lead to a change in the originating tensor. If the tensor is allocated on the GPU, PyTorch will make a copy of the content of the tensor into a NumPy array allocated on the CPU.



In [31]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
import h5py